[package]
authors = ["Ivan Enderlin <ivan@mnt.io>"]
edition = "2021"
name = "matrix-sdk-extensions"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
rust-version = { workspace = true }
version = "0.0.1"

[features]
default = ["native", "javascriptcore"]
native = ["dep:wasmtime", "matrix-sdk-extensions-macros/wasmtime"]
javascriptcore = ["dep:javascriptcore", "matrix-sdk-extensions-macros/javascriptcore"]

[dependencies]
matrix-sdk-extensions-macros = { path = "../matrix-sdk-extensions-macros", default-features = false }
wasmtime = { version ="13.0.0", features = ["component-model"], optional = true }
# javascriptcore = { git = "https://github.com/endoli/javascriptcore.rs", branch = "main", optional = true }
javascriptcore = { git = "https://github.com/Hywan/javascriptcore.rs", branch = "feat-macros-generics", optional = true }
anyhow.workspace = true
